title: "Teesta Naskar"
author: "Teesta Naskar"
description: "Neuroscientist"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: fasle        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Teesta Naskar_CV.pdf", title: "CV", icon: Home}
  - {title: "About me", icon: Home}
  - {title: "Publication", file: "Publication.md"}
  - {title: "Award", file: "Award.md"}
  - {title: "Talk", file: "Talk.md"}
  - {title: "Teaching & Mentoring", file: "mentoring.md"}
  - {title: "Event organization", file: "organization.md"}
  - {title: "Public outreach", file: "publicoutreach.md"}
  - {title: "Media", file: "Media.md"}
  - {title: "Personal Blog", file: "blog"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:teesnadi@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/TeestaNaskar?tab=repositories"}
  - {title: Twitter, icon: twitter, url: "https://x.com/teesta_neuro"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
